language: node_js

services:
  - cassandra

node_js:
  - "5"
  - "5.1"
  - "6.2"
  - "iojs"
  
before_install:
  - sudo wget https://raw.githubusercontent.com/weaviate/weaviate-cassandra/master/skeleton.cql
  - sudo cqlsh -f skeleton.cql

before_script:
  - npm install -g gulp
  - npm install -g forever
  - forever start example.js

script:
  - gulp validate
  - mocha
