language: node_js

services:
  - cassandra

node_js:
  - "5"
  - "5.1"
  - "5.2"
  - "5.3"
  - "5.4"
  - "5.5"
  - "5.6"
  - "5.7"
  - "5.8"
  - "5.9"
  - "5.10"
  - "5.11"
  - "6.0"
  - "6.1"
  - "6.2"
  - "6.3"
  
before_install:
  - sudo wget https://raw.githubusercontent.com/weaviate/weaviate-cassandra/master/skeleton.cql
  - sudo cqlsh -f skeleton.cql

before_script:
  - npm install -g gulp
  - npm install -g mocha
  - npm install -g forever
  - forever start ./examples/example_Bigtable.js

script:
  - gulp validate
  - mocha
